openapi: 3.0.0
info:
  title: Kleintierauffangstation
  version: '1.0'
  contact:
    name: Melissa Schwedes
    email: meli.sch09@gmail.com
  description: |-
    Diese App für eine Kleintierauffangstation nutzt einen REST-Webservice zur Kommunikation mit dem Backend. Die Daten der Kleintiere können angezeigt, gesucht, bearbeitet oder gelöscht werden. Das Gleiche gilt für die Pflegekräfte.
    Die Kleintiere besitzen jeweils Details zu Name, Geschlecht, Alter, Rasse und gesundheitlichem Zustand. Eine Pflegekraft besitzt einen Vornamen, Nachname, eine Rolle und eine Emailadresse.
servers:
  - url: 'http://localhost:3000'
paths:
  /:
    get:
      summary: Wurzeladresse des Webservices
      tags:
        - Index
      operationId: index
      description: liefert eine HATEOAS-Übersicht aller Collections
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json
  /kleintiere:
    get:
      summary: Kleintiere anzeigen
      tags:
        - Kleintiere
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Kleintiere'
                x-content-type: application/json
      operationId: search-kleintiere
      description: 'Alle Kleintiere die aktell in der Kleintierauffangstation sind, werden angezeigt'
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: Name des Tieres
          explode: true
          style: form
        - schema:
            type: string
          in: query
          name: alter
          description: geschätztes Alter des Tieres
          explode: true
          style: form
        - schema:
            type: string
          in: query
          name: geschlecht
          description: Geschlecht des Tieres
          explode: true
          style: form
        - schema:
            type: string
          in: query
          name: zustand
          description: gesundheitlicher Zustand
          explode: true
          style: form
        - schema:
            type: string
          in: query
          name: rasse
          description: Rasse des Tieres
          explode: true
          style: form
    post:
      summary: Kleintier in Klinik aufnehmen
      tags:
        - Kleintiere
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kleintiere'
      operationId: post-kleintiere
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kleintiere'
      description: Neues Kleintier aufnehmen
  /kleintiere/{id}:
    get:
      summary: Kleintier auswählen
      tags:
        - Kleintiere
      parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        style: simple
        explode: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kleintiere'
        '404':
          description: Not Found
      operationId: get-kleintiere-id
      description: Einzelne Kleintierdaten
    put:
      summary: Kleintierinformationen ersetzen
      tags:
        - Kleintiere
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kleintiere'
        '404':
          description: Not Found
      operationId: put-kleintiere-id
      description: Änderung Tierdaten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kleintiere'
    patch:
      summary: Einzelne Details verändern
      tags:
        - Kleintiere
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kleintiere'
        '404':
          description: Not Found
      operationId: patch-kleintiere-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Kleintiere'
      description: Änderung einzelner Attribute
    delete:
      summary: Kleintierdaten löschen
      tags:
        - Kleintiere
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: delete-kleintiere-id
      description: Löschen der Daten eines Kleintieres
  /pflegekraft:
    get:
      summary: Pflegekraefte anzeigen
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pflegekrafte'
                x-content-type: application/json
      operationId: get-pflegekraft
      tags:
        - Pflegekraft
      parameters:
        - schema:
            type: string
          in: query
          name: vorname
          description: Vorname des Mitarbeiters
          style: form
          explode: true
        - schema:
            type: string
          in: query
          name: nachname
          description: Nachname des Mitarbeiters
          style: form
          explode: true
        - schema:
            type: string
          in: query
          name: rolle
          description: Rolle der Pflegekraft
          style: form
          explode: true
        - schema:
            type: string
          in: query
          name: eMail
          description: E-Mail der Pflegekraft
          style: form
          explode: true
      description: Liste der aktuell angestellten Pflegekräften
    post:
      summary: Neue Pflegekraft anlegen
      tags:
        - Pflegekräfte
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pflegekrafte'
      operationId: post-pflegekraft
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pflegekrafte'
      description: Neue Pflegekraft anlegen
  /pflegekraft/{id}:
    get:
      summary: Pflegekraft auswählen
      tags:
        - Pflegekraft
      parameters:
      - name: id
        in: path
        style: simple
        explode: false
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pflegekrafte'
      operationId: get-pflegekraft-id
      description: Anzeige einer Pflegekraft
    put:
      summary: Pflegekraftdaten ersetzen
      tags:
        - Pflegekraft
      parameters:
      - name: id
        in: path
        style: simple
        explode: false
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pflegekrafte'
        '404':
          description: Not Found
      operationId: put-pflegekraft-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pflegekrafte'
      description: Datenänderung einer Pflegekraft
    patch:
      summary: Einzelne Daten einer Pflegekraft ändern
      tags:
        - Pflegekraft
      parameters:
      - name: id
        in: path
        style: simple
        explode: false
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pflegekrafte'
        '404':
          description: Not Found
      operationId: patch-pflegekraft-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pflegekrafte'
      description: Ändern eines einzelnen Attributes von einer Pflegekraft
    delete:
      summary: Pflegekraftdaten löschen
      tags:
        - Pflegekraft
      parameters:
      - name: id
        in: path
        style: simple
        explode: false
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: delete-pflegekraft-id
      description: Löschen der Daten einer Pflegekraft

components:
  schemas:
    Kleintiere:
      title: Kleintiere
      type: object
      properties:
        _link:
          $ref: '#/components/schemas/HATEOS_Resource'
        id:
          type: integer
        name:
          type: string
        geschlecht:
          type: string
        alter:
          type: integer
        zustand:
          type: string
        rasse:
          type: string
    Pflegekrafte:
      title: Pflegekrafte
      type: object
      properties:
        id:
          type: integer
        vorname:
          type: string
        nachname:
          type: string
        eMail:
          type: string
        rolle:
          type: string
    HATEOAS_Collection:
      title: HATEOAS_Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'
    HATEOS_Resource:
      title: HATEOS_Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        upade:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
    HATEOAS_Link:
      title: HATEOAS_Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string
tags:
  - name: Index
  - name: Kleintiere
  - name: Pflegekraft
